class StarData {
  final String element;
  final Map<int, String> statusMap;
  const StarData(this.element, this.statusMap);
}

const Map<String, StarData> phuTinhData = {
  'THIÊN KHÔI': StarData('HOA', {}),
  'ĐẠI HAO': StarData('HOA', {2: 'Đ', 8: 'Đ', 3: 'Đ', 9: 'Đ', 0: 'H', 1: 'H', 4: 'H', 5: 'H', 6: 'H', 7: 'H', 10: 'H', 11: 'H'}),
  'THIÊN VIỆT': StarData('HOA', {}),
  'TIỂU HAO': StarData('HOA', {2: 'Đ', 8: 'Đ', 3: 'Đ', 9: 'Đ', 0: 'H', 1: 'H', 4: 'H', 5: 'H', 6: 'H', 7: 'H', 10: 'H', 11: 'H'}),
  'TẢ PHỤ': StarData('THO', {}),
  'ĐẨU QUÂN': StarData('HOA', {}),
  'HỮU BẬT': StarData('THUY', {}),
  'LƯU HÀ': StarData('THUY', {}),
  'HÓA QUYỀN': StarData('MOC', {10: 'V', 1: 'V', 3: 'V', 4: 'Đ', 11: 'Đ', 5: 'Đ', 6: 'Đ', 2: 'Đ', 7: 'Đ', 0: 'B', 9: 'B', 8: 'B'}),
  'HÓA KỊ': StarData('THUY', {4: 'Đ', 10: 'Đ', 1: 'Đ', 7: 'Đ', 11: 'H', 9: 'H', 2: 'H', 5: 'H', 8: 'H', 3: 'H', 6: 'H', 0: 'H'}),
  'HÓA KHOA': StarData('MOC', {4: 'V', 1: 'V', 10: 'V', 0: 'Đ', 6: 'Đ', 8: 'Đ', 7: 'Đ', 2: 'Đ', 11: 'Đ', 3: 'Đ', 9: 'Đ', 5: 'Đ'}),
  'ĐỊA KHÔNG': StarData('HOA', {2: 'Đ', 8: 'Đ', 5: 'Đ', 11: 'Đ', 0: 'H', 1: 'H', 3: 'H', 4: 'H', 6: 'H', 7: 'H', 9: 'H', 10: 'H'}),
  'HÓA LỘC': StarData('MOC', {4: 'V', 1: 'V', 10: 'V', 3: 'Đ', 9: 'Đ', 7: 'Đ', 8: 'Đ', 2: 'Đ', 11: 'Đ', 5: 'Đ', 0: 'B', 6: 'B'}),
  'ĐỊA KIẾP': StarData('HOA', {2: 'Đ', 8: 'Đ', 5: 'Đ', 11: 'Đ', 0: 'H', 1: 'H', 3: 'H', 4: 'H', 6: 'H', 7: 'H', 9: 'H', 10: 'H'}),
  'LỰC SĨ': StarData('HOA', {}),
  'KÌNH DƯƠNG': StarData('KIM', {4: 'Đ', 10: 'Đ', 1: 'Đ', 7: 'Đ', 3: 'H', 6: 'H', 9: 'H', 0: 'H'}),
  'LỘC TỒN': StarData('THO', {0: 'M', 3: 'M', 6: 'M', 2: 'M', 5: 'Đ', 11: 'Đ', 9: 'B', 8: 'B'}),
  'ĐÀ LA': StarData('KIM', {4: 'Đ', 10: 'Đ', 1: 'Đ', 7: 'Đ', 2: 'H', 5: 'H', 8: 'H', 11: 'H'}),
  'THIÊN MÃ': StarData('HOA', {5: 'Đ', 2: 'Đ', 8: 'H', 11: 'H'}),
  'LINH TINH': StarData('HOA', {2: 'Đ', 3: 'Đ', 4: 'Đ', 5: 'Đ', 6: 'Đ', 7: 'H', 8: 'H', 9: 'H', 10: 'H', 11: 'H', 0: 'H', 1: 'H'}),
  'HOA CÁI': StarData('KIM', {}),
  'HỎA TINH': StarData('HOA', {2: 'Đ', 3: 'Đ', 4: 'Đ', 5: 'Đ', 6: 'Đ', 7: 'H', 8: 'H', 9: 'H', 10: 'H', 11: 'H', 0: 'H', 1: 'H'}),
  'THANH LONG': StarData('THUY', {}),
  'QUAN PHÙ': StarData('HOA', {}),
  'LONG TRÌ': StarData('THUY', {}),
  'QUAN PHỦ': StarData('HOA', {}),
  'PHƯỢNG CÁC': StarData('MOC', {}),
  'PHI LIÊM': StarData('HOA', {}),
  'TẤU THƯ': StarData('KIM', {}),
  'BẠCH HỔ': StarData('KIM', {2: 'Đ', 8: 'Đ', 3: 'Đ', 9: 'Đ', 0: 'H', 1: 'H', 4: 'H', 5: 'H', 6: 'H', 7: 'H', 10: 'H', 11: 'H'}),
  'VĂN XƯƠNG': StarData('KIM', {5: 'M', 9: 'M', 1: 'M', 11: 'Đ', 0: 'Đ', 8: 'Đ', 4: 'Đ', 7: 'Đ', 3: 'Đ', 2: 'H', 6: 'H', 10: 'H'}),
  'TANG MÔN': StarData('MOC', {2: 'Đ', 8: 'Đ', 3: 'Đ', 9: 'Đ', 0: 'H', 1: 'H', 4: 'H', 5: 'H', 6: 'H', 7: 'H', 10: 'H', 11: 'H'}),
  'VĂN KHÚC': StarData('THUY', {0: 'M', 5: 'M', 9: 'M', 1: 'M', 11: 'V', 7: 'V', 3: 'Đ', 8: 'Đ', 4: 'Đ', 2: 'B', 6: 'H', 10: 'H'}),
  'CÔ THẦN': StarData('THO', {}),
  'LN VĂN TINH': StarData('HOA', {}),
  'QUẢ TÚ': StarData('THO', {}),
  'THIÊN Y': StarData('THUY', {}),
  'THIÊN DIÊU': StarData('THUY', {2: 'Đ', 3: 'Đ', 9: 'Đ', 10: 'Đ', 0: 'H', 1: 'H', 4: 'H', 5: 'H', 6: 'H', 7: 'H', 8: 'H', 11: 'H'}),
  'ÂN QUANG': StarData('MOC', {}),
  'THIÊN KHỐC': StarData('THUY', {0: 'Đ', 6: 'Đ', 3: 'Đ', 9: 'Đ', 1: 'Đ', 7: 'Đ', 2: 'H', 8: 'H', 5: 'H', 11: 'H', 4: 'H', 10: 'H'}),
  'THIÊN QUÝ': StarData('THO', {}),
  'THIÊN HƯ': StarData('THUY', {0: 'Đ', 6: 'Đ', 3: 'Đ', 9: 'Đ', 1: 'Đ', 7: 'Đ', 2: 'H', 8: 'H', 5: 'H', 11: 'H', 4: 'H', 10: 'H'}),
  'TAM THAI': StarData('THUY', {}),
  'THIÊN THƯƠNG': StarData('THO', {}),
  'BÁT TỌA': StarData('MOC', {}),
  'THIÊN SỨ': StarData('THUY', {}),
  'THAI PHỤ': StarData('KIM', {}),
  'THIÊN LA': StarData('THO', {}),
  'PHONG CÁO': StarData('THO', {}),
  'ĐỊA VÕNG': StarData('THO', {}),
  'BÁC SỸ': StarData('THUY', {}),
  'THÁI TUẾ': StarData('HOA', {}),
  'HỈ THẦN': StarData('HOA', {}),
  'TUẾ PHÁ': StarData('HOA', {}),
  'THIÊN HỶ': StarData('THUY', {}),
  'PHÁ TOÁI': StarData('KIM', {}),
  'ĐÀO HOA': StarData('MOC', {}),
  'THIÊN KHÔNG': StarData('HOA', {}),
  'HỒNG LOAN': StarData('KIM', {}),
  'KIẾP SÁT': StarData('HOA', {}),
  'THIÊN TÀI': StarData('THO', {}),
  'TỬ PHÙ': StarData('HOA', {}),
  'THIÊN THỌ': StarData('THO', {}),
  'TRỰC PHÙ': StarData('HOA', {}),
  'THIÊN ĐỨC': StarData('HOA', {}),
  'BỆNH PHÙ': StarData('MOC', {}),
  'NGUYỆT ĐỨC': StarData('HOA', {}),
  'ĐIẾU KHÁCH': StarData('HOA', {}),
  'LONG ĐỨC': StarData('THUY', {}),
  'PHÚC ĐỨC': StarData('THO', {}),
  'THIÊN QUAN': StarData('HOA', {}),
  'THIÊN PHÚC': StarData('THO', {}),
  'THIÊN GIẢI': StarData('HOA', {}),
  'ĐỊA GIẢI': StarData('THO', {}),
  'GIẢI THẦN': StarData('MOC', {}),
  'ĐƯỜNG PHÙ': StarData('MOC', {}),
  'TƯỚNG QUÂN': StarData('MOC', {}),
  'QUỐC ẤN': StarData('THO', {}),
  'THIÊN HÌNH': StarData('HOA', {2: 'Đ', 8: 'Đ', 3: 'Đ', 9: 'Đ', 0: 'H', 1: 'H', 4: 'H', 5: 'H', 6: 'H', 7: 'H', 10: 'H', 11: 'H'}),
  'THIẾU DƯƠNG': StarData('HOA', {}),
  'PHỤC BINH': StarData('HOA', {}),
  'THIẾU ÂM': StarData('THUY', {}),
  'THIÊN TRÙ': StarData('THO', {}),
};
